name: C/C++ CI

on:
  push:
    branches:
      - master
      - dev
      - Trying-out-CI
  pull_request:
    branches: 
      - master
      - dev
      - Trying-out-CI

jobs:

  # Add build_redhat, no redhat virtual environment currently supported by GitHub Actions

  build_ubuntu:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install g++ compiler
      run: apt-get install g++
    - name: Install GSL
      run: apt-get install libgsl-dev
    - name: Make COMPAS
      run: make
      working-directory: ./src
    - name: Run COMPAS
      run: ./COMPAS -n 1000 --random-seed 0
      working-directory: ./src

  build_macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install GSL
      run: brew install gsl
    - name: Install Boost
      run: brew install boost
    - name: Make COMPAS
      run: make
      working-directory: ./src
#   
#     - name: Make clean
#       run: make clean 
#       working-directory: ./src
#     - name: Make fast COMPAS
#       run: make fast -j $(nproc)
#       working-directory: ./src
    - name: Run COMPAS
      run: ./COMPAS -n 1000 --random-seed 0
      working-directory: ./src

  
