name: C/C++ CI

on:
  push:
    branches:
      - master
      - dev
      - Trying-out-CI
  pull_request:
    branches: 
      - master
      - dev
      - Trying-out-CI

jobs:

  build_macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install GSL
      run: brew install gsl
    - name: Install Boost
      run: brew install boost
    - name: Print current working directory
      run: pwd
    - name: Change to source directory
      run: cd ./src
    - name: Print current working directory
      run: pwd
    - name: Make COMPAS
      run: make -j $(nproc)
      working-directory: ./src
    - name: Make clean
      run: make clean 
      working-directory: ./src
    - name: Make fast COMPAS
      run: make fast -j $(nproc)
      working-directory: ./src
    - name: Run COMPAS
      run: ./COMPAS -n 1000 --random-seed 0
      working-directory: ./src

  
